# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-16 22:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stu_crm', '0002_auto_20171017_0634'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='pone',
            new_name='phone',
        ),
    ]
