# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-18 06:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stu_crm', '0003_auto_20171017_0635'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'permissions': (('view_customer_list', '可以查看客户列表'), ('view_customer_info', '可以查看客户详情'), ('edit_own_customer_info', '可以修改自己客户信息'))},
        ),
    ]
