# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-09 08:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_auto_20170927_1153'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='athor',
            options={'verbose_name_plural': '作者'},
        ),
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name_plural': '书名'},
        ),
        migrations.AlterModelOptions(
            name='publisher',
            options={'verbose_name_plural': '出版社'},
        ),
        migrations.AlterField(
            model_name='publisher',
            name='country',
            field=models.CharField(editable=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='state_province',
            field=models.CharField(help_text='所在国家省份', max_length=30, verbose_name='所属省'),
        ),
    ]
